//根
export const UPDATE_OPENID = 'UPDATE_OPENID'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'


//问题
export const ADD_PROBLEM = 'ADD_PROBLEM'
export const UPDATE_PROBLEM = 'UPDATE_PROBLEM'
export const UPDATE_PROBLEM_LOAD_END = 'UPDATE_PROBLEM_LOAD_END'
export const UPDATE_PROBLEM_START = 'UPDATE_PROBLEM_START'
export const UPDATE_PROJECT_NAME = 'UPDATE_PROJECT_NAME'
export const UPDATE_SUBPROJECT_NAME = 'UPDATE_SUBPROJECT_NAME'
export const UPDATE_CHARGER_NAME = 'UPDATE_CHARGER_NAME'
export const UPDATE_CREATOR_NAME = 'UPDATE_CREATOR_NAME'
export const UPDATE_PROBLEM_QUERY_PARAMS = 'UPDATE_PROBLEM_QUERY_PARAMS'

//我的问题
export const ADD_MY_PROBLEM = 'ADD_MY_PROBLEM'
export const UPDATE_MY_PROBLEM = 'UPDATE_MY_PROBLEM'
export const UPDATE_MY_PROBLEM_LOAD_END = 'UPDATE_MY_PROBLEM_LOAD_END'
export const UPDATE_MY_PROBLEM_START = 'UPDATE_MY_PROBLEM_START'

export const ADD_PROJECT_LIST = 'ADD_PROJECT_LIST'
export const UPDATE_PROJECT_START = 'UPDATE_PROJECT_START'
export const UPDATE_PROJECT_LOAD_END = 'UPDATE_PROJECT_LOAD_END'
export const ADD_MY_PROJECT_LIST = 'ADD_MY_PROJECT_LIST'
export const UPDATE_MY_PROJECT_START = 'UPDATE_MY_PROJECT_START'
export const UPDATE_MY_PROJECT_LOAD_END = 'UPDATE_MY_PROJECT_LOAD_END'
export const UPDATE_PROJECT_FLOW_STATES = 'UPDATE_PROJECT_FLOW_STATES'

export const UPDATE_TASK_SCROLLTOP = 'UPDATE_TASK_SCROLLTOP'

