//根
export const UPDATE_OPENID = 'UPDATE_OPENID'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const UPDATE_USER_STATISTICS = 'UPDATE_USER_STATISTICS'

//所有问题
export const ADD_PROBLEM = 'ADD_PROBLEM'
export const UPDATE_PROBLEM = 'UPDATE_PROBLEM'
export const UPDATE_PROBLEM_LOAD_END = 'UPDATE_PROBLEM_LOAD_END'
export const UPDATE_PROBLEM_START = 'UPDATE_PROBLEM_START'
export const UPDATE_PROJECT_NAME = 'UPDATE_PROJECT_NAME'
export const UPDATE_SUBPROJECT_NAME = 'UPDATE_SUBPROJECT_NAME'
export const UPDATE_CHARGER_NAME = 'UPDATE_CHARGER_NAME'
export const UPDATE_CREATOR_NAME = 'UPDATE_CREATOR_NAME'
export const UPDATE_PROBLEM_QUERY_PARAMS = 'UPDATE_PROBLEM_QUERY_PARAMS'

//我的问题
export const ADD_MY_PROBLEM = 'ADD_MY_PROBLEM'
export const UPDATE_MY_PROBLEM = 'UPDATE_MY_PROBLEM'
export const UPDATE_MY_PROBLEM_LOAD_END = 'UPDATE_MY_PROBLEM_LOAD_END'
export const UPDATE_MY_PROBLEM_START = 'UPDATE_MY_PROBLEM_START'


//子项目问题
export const ADD_PROJECT_PROBLEM = 'ADD_PROJECT_PROBLEM'
export const UPDATE_PROJECT_PROBLEM = 'UPDATE_PROJECT_PROBLEM'
export const UPDATE_PROJECT_PROBLEM_LOAD_END = 'UPDATE_PROJECT_PROBLEM_LOAD_END'
export const UPDATE_PROJECT_PROBLEM_START = 'UPDATE_PROJECT_PROBLEM_START'

//项目
export const ADD_PROJECT_LIST = 'ADD_PROJECT_LIST'
export const UPDATE_PROJECT_LIST = 'UPDATE_PROJECT_LIST'
export const UPDATE_PROJECT_START = 'UPDATE_PROJECT_START'
export const UPDATE_PROJECT_LOAD_END = 'UPDATE_PROJECT_LOAD_END'

//我的项目
export const ADD_MY_PROJECT_LIST = 'ADD_MY_PROJECT_LIST'
export const UPDATE_MY_PROJECT_LIST = 'UPDATE_MY_PROJECT_LIST'
export const UPDATE_MY_PROJECT_START = 'UPDATE_MY_PROJECT_START'
export const UPDATE_MY_PROJECT_LOAD_END = 'UPDATE_MY_PROJECT_LOAD_END'

//任务
export const ADD_TASK_GROUP_LIST = 'ADD_TASK_GROUP_LIST'
export const UPDATE_TASK_GROUP_LIST = 'UPDATE_TASK_GROUP_LIST'
export const UPDATE_TASK_GROUP_START = 'UPDATE_TASK_GROUP_START'
export const UPDATE_TASK_GROUP_LOAD_END = 'UPDATE_TASK_GROUP_LOAD_END'

//我的任务
export const ADD_MY_TASK_LIST = 'ADD_MY_TASK_LIST'
export const UPDATE_MY_TASK_LIST = 'UPDATE_MY_TASK_LIST'
export const UPDATE_MY_TASK_START = 'UPDATE_MY_TASK_START'
export const UPDATE_MY_TASK_LOAD_END = 'UPDATE_MY_TASK_LOAD_END'
export const UPDATE_MY_TASK_TASK_GROUP_NAMES = 'UPDATE_MY_TASK_TASK_GROUP_NAMES'

//项目人员的任务
export const ADD_STAFF_TASK_LIST = 'ADD_STAFF_TASK_LIST'
export const UPDATE_STAFF_TASK_LIST = 'UPDATE_STAFF_TASK_LIST'
export const UPDATE_STAFF_TASK_START = 'UPDATE_STAFF_TASK_START'
export const UPDATE_STAFF_TASK_LOAD_END = 'UPDATE_STAFF_TASK_LOAD_END'

//子项目详细信息
export const UPDATE_SUBPROJECT_DETAIL = 'UPDATE_SUBPROJECT_DETAIL'
export const UPDATE_PROJECT_FLOW_STATES = 'UPDATE_PROJECT_FLOW_STATES'
export const UPDATE_PROJECT_TIME_LINES = 'UPDATE_PROJECT_TIME_LINES'
export const UPDATE_SUBPROJECT_PROBLEM_STATISTICS = 'UPDATE_SUBPROJECT_PROBLEM_STATISTICS'
export const UPDATE_SUBPROJECT_TASK_STATISTICS = 'UPDATE_SUBPROJECT_TASK_STATISTICS'
export const UPDATE_SUBPROJECT_STAFF_LIST = 'UPDATE_SUBPROJECT_STAFF_LIST'

//任务的详细信息
export const UPDATE_TASK_DETAIL = 'UPDATE_TASK_DETAIL'

//问题的详细信息
export const UPDATE_PROBLEM_DETAIL = 'UPDATE_PROBLEM_DETAIL'
